server:
  port: 8080

dubbo:
  application:
    name: cyqTest
  protocol:
    dispatcher: message
    name: dubbo
    port: -1
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
    register: false
  config-center:
    timeout: 5000
  scan:
    basePackages: com.guahoa.cyqTest.dubbo
  provider:
    timeout: 3000
  consumer:
    timeout: 3000
    check: false
